apiVersion: v1
kind: Secret
metadata:
  name: issuer-base-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |
    email: {{ .Values.issuer.acme.email }}
    server: {{ .Values.issuer.acme.server }}
