apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: garden-install
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: garden-config
  sourceRef:
    kind: GitRepository
    name: 23ke
  path: ./garden-install
  prune: true
  validation: client
