{{- $ca := genCA "my-CA" 3650 }}
{{- $admissioncert := genSignedCert "example.net" (list "127.0.0.1") (list "localhost" "gardener-admission-controller" "gardener-admission-controller.garden" "gardener-admission-controller.garden.svc") 3650 $ca }}
{{- $apiservercert := genSignedCert "example.net" (list "127.0.0.1") (list "localhost" "gardener-apiserver" "gardener-apiserver.garden" "gardener-apiserver.garden.svc") 3650 $ca }}
{{- $etcdclientcert := genSignedCert "etcd-client" nil ( list "etcd-client" ) 3650 $ca }}
{{- $etcdservercert := genSignedCert "etcd" nil ( list "etcd" ) 3650 $ca }}
{{- $kubeapiservercert := genSignedCert "kubernetes" (list "127.0.0.1") (list "localhost" "kubernetes.default" "garden-kube-apiserver" "garden-kube-apiserver.garden" "garden-kube-apiserver.garden.svc" "vgarden.demo.cc.gardendev.link") 3650 $ca }}
{{- $kubecontrollercert := genSignedCert "system:kube-controller-manager" nil nil 3650 $ca }}
{{- $kubeadmincert := genSignedCert "garden:client:admin.system:masters" nil nil 3650 $ca }}
{{- $kubeaggregatorcert := genSignedCert "garden:aggregator-client:kube-aggregator" nil nil 3650 $ca }}
{{- $kubeserviceaccountkey := genPrivateKey "rsa" }}



---
apiVersion: v1
kind: Secret
metadata:
  name: gardener-base-secret-values
  namespace: garden
type: Opaque
stringData:
  gardener-base-secret-values.yaml: |
    global:
      apiserver:
        etcd:
          caBundle: |
{{ indent 12 $ca.Cert }}
          tls:
            crt: |
{{ indent 14 $etcdclientcert.Cert }}
            key: |
{{ indent 14 $etcdclientcert.Key }}
        tls:
          crt: |
{{ indent 12 $apiservercert.Cert }}
          key: |
{{ indent 12 $apiservercert.Key }}
      admission:
        config:
          server:
            https:
              tls:
                caBundle: |
{{ indent 18 $ca.Cert }}
                crt: |
{{ indent 18 $admissioncert.Cert }}
                key: |
{{ indent 18 $admissioncert.Key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: garden-etcd-base-secret-values
  namespace: garden
type: Opaque
stringData:
  values.yaml: |-
    tls:
      ca:
        crt: |-
{{ indent 10 $ca.Cert }}
        key: invalid
      server:
        crt: |-
{{ indent 10 $etcdservercert.Cert }}
        key: |-
{{ indent 10 $etcdservercert.Key }}
      client:
        crt: |-
{{ indent 10 $etcdclientcert.Cert }}
        key: |-
{{ indent 10 $etcdclientcert.Key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: garden-kube-apiserver-base-secret-values
  namespace: garden
type: Opaque
stringData:
  values.yaml: |-
    tls:
      kubeAPIServer:
        ca:
          crt: |
{{ indent 12 $ca.Cert }}
          key: |
{{ indent 12 $ca.Key }}
        server:
          crt: |
{{ indent 12 $kubeapiservercert.Cert }}
          key: |
{{ indent 12 $kubeapiservercert.Key }}
      kubeControllerManager:
        crt: |
{{ indent 12 $kubecontrollercert.Cert }}
        key: |
{{ indent 12 $kubecontrollercert.Key }}
      admin:
        crt: |
{{ indent 12 $kubeadmincert.Cert }}
        key: |
{{ indent 12 $kubeadmincert.Key }}
      serviceAccountKey: |
{{ indent 12 $kubeserviceaccountkey }}
      kubeAggregator:
        ca:
          crt: |
{{ indent 12 $ca.Cert }}
          key: |
{{ indent 12 $ca.Key }}
        client:
          crt: |
{{ indent 12 $kubeaggregatorcert.Cert }}
          key: |
{{ indent 12 $kubeaggregatorcert.Key }}
