apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: garden-etcd
  namespace: garden
spec:
  interval: 1m
  dependsOn:
    - name: gardener-base-secret-values
  chart:
    spec:
      chart: ./helmcharts/garden-etcd/
      sourceRef:
        kind: GitRepository
        name: 23ke
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  valuesFrom:
  - kind: Secret
    name: garden-etcd-base-secret-values
    optional: false
