apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gardener-base-secret-values
  namespace: garden
spec:
  interval: 5m
  chart:
    spec:
      chart: ./garden-config/gardener-base-secret-values-chart
      sourceRef:
        kind: GitRepository
        name: 23ke
        namespace: flux-system
      interval: 1m
