---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: gardener-base-values
  namespace: garden
data:
  gardener-base-values.yaml: |-
    global:
      deployment:
        virtualGarden:
          enabled: false
          clusterIP: 10.96.0.20
      internalDomain:
        domain: example.org
        provider: aws-route53 # depends on the DNS extension of your choice
      apiserver:
        replicaCount: 1
        clusterIdentity: garden-cluster-identity
        image:
          tag: v1.20.0
        etcd:
          servers: https://etcd:2379
        # Don't care about certificates for local development scenario
        insecureSkipTLSVerify: true
        caBundle: ""
      # Gardener admission controller configuration values
      admission:
        replicaCount: 1
        image:
          tag: v1.20.0
      # Gardener controller manager configuration values
      controller:
        replicaCount: 1
        image:
          tag: v1.20.0
      scheduler:
        replicaCount: 1
        image:
          tag: v1.20.0
