---
apiVersion: v1
kind: ConfigMap
metadata:
  name: extensions-base-values
  namespace: flux-system
data:
  values.yaml: |-
    os-ubuntu:
      version: 1.18.0

    os-gardenlinux:
      version: 0.14.0

    provider-hcloud:
      version: 0.5.7

    provider-azure:
      version: 1.29.0
      admission: true

    provider-openstack:
      version: 1.28.0
      admission: true

    networking-calico:
      version: 1.26.0

    shoot-cert-service:
      version: 1.24.0

    shoot-dns-service:
      version: 1.24.0
      enabled: true
      globallyEnabled: true
      values:
        dnsControllerManager:
          deploy: true
          image:
            repository: eu.gcr.io/gardener-project/dns-controller-manager
            tag: v0.13.1
          configuration:
            cacheTtl: 300
            controllers: dnscontrollers,dnssources
            dnsPoolResyncPeriod: 30m
            serverPortHttp: 8080

    external-dns-management:
      version: 0.13.1
      enabled: false
