apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/gardener/gardener-extension-provider-azure/v1.18.1/example/controller-registration.yaml
- https://raw.githubusercontent.com/gardener/gardener-extension-networking-calico/v1.15.0/example/controller-registration.yaml
- https://raw.githubusercontent.com/gardener/external-dns-management/v0.8.0/examples/controller-registration.yaml
- https://raw.githubusercontent.com/gardener/gardener-extension-os-gardenlinux/v0.8.0/example/controller-registration.yaml
- https://raw.githubusercontent.com/gardener/gardener-extension-shoot-dns-service/v1.9.0/example/controller-registration.yaml
- https://raw.githubusercontent.com/gardener/gardener-extension-shoot-cert-service/v1.11.0/example/controller-registration.yaml
- admin-clusterrolebinding.yaml
- 00-namespace-garden-dev.yaml
- 05-project-dev.yaml
- cloudprofile-azure.yaml
#- cloudprofile-openstack.yaml
