apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 23ke-infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: Bucket
    name: 23ke
  path: ./infrastructure
  prune: false
  validation: client
